import { cn } from '@/utils/cn';

import './globals.css';

import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { TooltipProvider } from '@radix-ui/react-tooltip';
import { ThemeProvider } from 'next-themes';

import { Providers } from '@/app/providers';

const fontInter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'HR Management | Align UI',
  description: 'Generated by create next app',
  // robots: {
  //   index: false,
  //   follow: false,
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={cn(fontInter.className, 'bg-bg-white-0 antialiased')}
    >
      <body className='bg-bg-white-0'>
        <Providers>
          <ThemeProvider attribute='class'>
            <TooltipProvider
              delayDuration={100}
              skipDelayDuration={300}
              disableHoverableContent
            >
              {children}
            </TooltipProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
