// export default

export default {
  objects: {
    Accordion: [
      "Context",
      "Item",
      "ItemBody",
      "ItemContent",
      "ItemContext",
      "ItemIndicator",
      "ItemTrigger",
      "PropsProvider",
      "Root",
      "RootProvider",
    ],
    ActionBar: [
      "CloseTrigger",
      "Content",
      "Context",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "SelectionTrigger",
      "Separator",
    ],
    Alert: ["Content", "Description", "Indicator", "Root", "RootPropsProvider", "Title"],
    Avatar: ["Context", "Fallback", "Icon", "Image", "PropsProvider", "Root", "RootProvider"],
    Blockquote: ["Caption", "Content", "Icon", "PropsProvider", "Root"],
    Breadcrumb: ["CurrentLink", "Ellipsis", "Item", "Link", "List", "PropsProvider", "Root", "Separator"],
    Card: ["Body", "Description", "Footer", "Header", "PropsProvider", "Root", "Title"],
    Checkbox: [
      "Context",
      "Control",
      "Group",
      "HiddenInput",
      "Indicator",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
    ],
    CheckboxCard: [
      "Addon",
      "Content",
      "Context",
      "Control",
      "Description",
      "HiddenInput",
      "Indicator",
      "Label",
      "Root",
      "RootPropsProvider",
      "RootProvider",
    ],
    Clipboard: [
      "Context",
      "Control",
      "CopyText",
      "Indicator",
      "Input",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
      "ValueText",
    ],
    Collapsible: ["Content", "Context", "PropsProvider", "Root", "RootProvider", "Trigger"],
    ColorPicker: [
      "Area",
      "AreaBackground",
      "AreaThumb",
      "ChannelInput",
      "ChannelSlider",
      "ChannelSliderLabel",
      "ChannelSliderThumb",
      "ChannelSliderTrack",
      "ChannelSliderValueText",
      "ChannelText",
      "Content",
      "Context",
      "Control",
      "EyeDropper",
      "EyeDropperTrigger",
      "FormatSelect",
      "FormatTrigger",
      "HiddenInput",
      "Input",
      "Label",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Sliders",
      "Swatch",
      "SwatchGroup",
      "SwatchIndicator",
      "SwatchTrigger",
      "TransparencyGrid",
      "Trigger",
      "ValueSwatch",
      "ValueText",
      "View",
    ],
    Combobox: [
      "ClearTrigger",
      "Content",
      "Context",
      "Control",
      "Empty",
      "Indicator",
      "IndicatorGroup",
      "Input",
      "Item",
      "ItemContext",
      "ItemGroup",
      "ItemGroupLabel",
      "ItemIndicator",
      "ItemText",
      "Label",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
    ],
    DataList: ["Item", "ItemLabel", "ItemValue", "PropsProvider", "Root"],
    Dialog: [
      "ActionTrigger",
      "Backdrop",
      "Body",
      "CloseTrigger",
      "Content",
      "Context",
      "Description",
      "Footer",
      "Header",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Title",
      "Trigger",
    ],
    Drawer: [
      "ActionTrigger",
      "Backdrop",
      "Body",
      "CloseTrigger",
      "Content",
      "Context",
      "Description",
      "Footer",
      "Header",
      "Positioner",
      "Root",
      "RootPropsProvider",
      "RootProvider",
      "Title",
      "Trigger",
    ],
    EMPTY_SLOT_STYLES: [],
    EMPTY_STYLES: [],
    Editable: [
      "Area",
      "CancelTrigger",
      "Context",
      "Control",
      "EditTrigger",
      "Input",
      "Preview",
      "PropsProvider",
      "Root",
      "RootProvider",
      "SubmitTrigger",
      "Textarea",
    ],
    EmptyState: ["Content", "Description", "Indicator", "PropsProvider", "Root", "Title"],
    Field: ["ErrorIcon", "ErrorText", "HelperText", "Label", "PropsProvider", "RequiredIndicator", "Root"],
    Fieldset: ["Content", "Context", "ErrorText", "HelperText", "Legend", "Root"],
    FileUpload: [
      "ClearTrigger",
      "Context",
      "Dropzone",
      "DropzoneContent",
      "FileText",
      "HiddenInput",
      "Item",
      "ItemContent",
      "ItemDeleteTrigger",
      "ItemGroup",
      "ItemName",
      "ItemPreview",
      "ItemPreviewImage",
      "ItemSizeText",
      "Items",
      "Label",
      "List",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
    ],
    HoverCard: [
      "Arrow",
      "ArrowTip",
      "Content",
      "Context",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
    ],
    List: ["Indicator", "Item", "Root", "RootPropsProvider"],
    Menu: [
      "Arrow",
      "ArrowTip",
      "CheckboxItem",
      "Content",
      "Context",
      "ContextTrigger",
      "Indicator",
      "Item",
      "ItemCommand",
      "ItemContext",
      "ItemGroup",
      "ItemGroupLabel",
      "ItemIndicator",
      "ItemText",
      "Positioner",
      "RadioItem",
      "RadioItemGroup",
      "Root",
      "RootPropsProvider",
      "RootProvider",
      "Separator",
      "Trigger",
      "TriggerItem",
    ],
    NativeSelect: ["Field", "Indicator", "PropsProvider", "Root"],
    NumberInput: [
      "Context",
      "Control",
      "DecrementTrigger",
      "IncrementTrigger",
      "Input",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Scrubber",
      "ValueText",
    ],
    Pagination: [
      "Context",
      "Ellipsis",
      "Item",
      "Items",
      "NextTrigger",
      "PageText",
      "PrevTrigger",
      "PropsProvider",
      "Root",
      "RootProvider",
    ],
    PinInput: ["Context", "Control", "HiddenInput", "Input", "Label", "PropsProvider", "Root", "RootProvider"],
    Popover: [
      "Anchor",
      "Arrow",
      "ArrowTip",
      "Body",
      "CloseTrigger",
      "Content",
      "Context",
      "Description",
      "Footer",
      "Header",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Title",
      "Trigger",
      "usePopoverStyles",
    ],
    Progress: ["Context", "Label", "PropsProvider", "Range", "Root", "RootProvider", "Track", "ValueText"],
    ProgressCircle: ["Circle", "Label", "PropsProvider", "Range", "Root", "RootProvider", "Track", "ValueText"],
    QrCode: ["Context", "DownloadTrigger", "Frame", "Overlay", "Pattern", "PropsProvider", "Root", "RootProvider"],
    RadioCard: [
      "Context",
      "Item",
      "ItemAddon",
      "ItemContent",
      "ItemContext",
      "ItemControl",
      "ItemDescription",
      "ItemHiddenInput",
      "ItemIndicator",
      "ItemText",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
    ],
    RadioGroup: [
      "Context",
      "Item",
      "ItemContext",
      "ItemControl",
      "ItemHiddenInput",
      "ItemIndicator",
      "ItemText",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
    ],
    RatingGroup: [
      "Context",
      "Control",
      "HiddenInput",
      "Item",
      "ItemContext",
      "ItemIndicator",
      "Items",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
      "useRatingGroupStyles",
    ],
    SegmentGroup: [
      "Context",
      "Indicator",
      "Item",
      "ItemContext",
      "ItemHiddenInput",
      "ItemText",
      "Items",
      "PropsProvider",
      "Root",
      "RootProvider",
    ],
    Select: [
      "ClearTrigger",
      "Content",
      "Context",
      "Control",
      "HiddenSelect",
      "Indicator",
      "IndicatorGroup",
      "Item",
      "ItemContext",
      "ItemGroup",
      "ItemGroupLabel",
      "ItemIndicator",
      "ItemText",
      "Label",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
      "ValueText",
    ],
    Slider: [
      "Context",
      "Control",
      "DraggingIndicator",
      "HiddenInput",
      "Label",
      "Marker",
      "MarkerGroup",
      "MarkerIndicator",
      "Marks",
      "PropsProvider",
      "Range",
      "Root",
      "RootProvider",
      "Thumb",
      "Thumbs",
      "Track",
      "ValueText",
    ],
    Stat: ["DownIndicator", "HelpText", "Label", "PropsProvider", "Root", "UpIndicator", "ValueText", "ValueUnit"],
    Status: ["Indicator", "PropsProvider", "Root"],
    Steps: [
      "CompletedContent",
      "Content",
      "Context",
      "Description",
      "Indicator",
      "Item",
      "ItemContext",
      "List",
      "NextTrigger",
      "Number",
      "PrevTrigger",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Separator",
      "Status",
      "Title",
      "Trigger",
    ],
    Switch: [
      "Context",
      "Control",
      "HiddenInput",
      "Indicator",
      "Label",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Thumb",
      "ThumbIndicator",
    ],
    Table: [
      "Body",
      "Caption",
      "Cell",
      "Column",
      "ColumnGroup",
      "ColumnHeader",
      "Footer",
      "Header",
      "Root",
      "RootPropsProvider",
      "Row",
      "ScrollArea",
    ],
    Tabs: [
      "Content",
      "ContentGroup",
      "Context",
      "Indicator",
      "List",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
    ],
    Tag: ["CloseTrigger", "EndElement", "Label", "Root", "RootPropsProvider", "StartElement"],
    Timeline: [
      "Connector",
      "Content",
      "Description",
      "Indicator",
      "Item",
      "Root",
      "RootPropsProvider",
      "Separator",
      "Title",
    ],
    Toast: ["ActionTrigger", "CloseTrigger", "Description", "Indicator", "Root", "Title"],
    Toggle: ["Context", "Indicator", "PropsProvider", "Root"],
    Tooltip: [
      "Arrow",
      "ArrowTip",
      "Content",
      "Context",
      "Positioner",
      "PropsProvider",
      "Root",
      "RootProvider",
      "Trigger",
    ],
    defaultBaseConfig: ["conditions", "utilities"],
    defaultConfig: ["conditions", "utilities", "preflight", "cssVarsPrefix", "cssVarsRoot", "globalCss", "theme"],
    defaultSystem: [
      "$$chakra",
      "_config",
      "_global",
      "breakpoints",
      "tokens",
      "conditions",
      "utility",
      "token",
      "properties",
      "layers",
      "isValidProperty",
      "splitCssProps",
      "normalizeValue",
      "getTokenCss",
      "getGlobalCss",
      "getPreflightCss",
      "css",
      "cva",
      "sva",
      "getRecipe",
      "getSlotRecipe",
      "hasRecipe",
      "isRecipe",
      "isSlotRecipe",
    ],
    visuallyHiddenStyle: [
      "border",
      "clip",
      "height",
      "width",
      "margin",
      "padding",
      "overflow",
      "whiteSpace",
      "position",
    ],
  },
  symbols: {
    AbsoluteCenter: [
      "$$typeof",
      "render",
      "__emotion_real",
      "__emotion_base",
      "__emotion_forwardProp",
      "__emotion_cva",
    ],
    AccordionItem: ["$$typeof", "render"],
    AccordionItemBody: ["$$typeof", "render"],
    AccordionItemContent: ["$$typeof", "render"],
    AccordionItemIndicator: ["$$typeof", "render"],
    AccordionItemTrigger: ["$$typeof", "render"],
    AccordionPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    AccordionRoot: ["$$typeof", "render"],
    AccordionRootProvider: ["$$typeof", "render"],
    ActionBarCloseTrigger: ["$$typeof", "render"],
    ActionBarContent: ["$$typeof", "render"],
    ActionBarPositioner: ["$$typeof", "render"],
    ActionBarPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ActionBarSelectionTrigger: ["$$typeof", "render"],
    ActionBarSeparator: ["$$typeof", "render"],
    AlertContent: ["$$typeof", "render"],
    AlertDescription: ["$$typeof", "render"],
    AlertIndicator: ["$$typeof", "render"],
    AlertPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    AlertRoot: ["$$typeof", "render"],
    AlertTitle: ["$$typeof", "render"],
    AspectRatio: ["$$typeof", "render"],
    AvatarFallback: ["$$typeof", "render"],
    AvatarGroup: ["$$typeof", "render"],
    AvatarIcon: ["$$typeof", "render"],
    AvatarImage: ["$$typeof", "render"],
    AvatarPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    AvatarRoot: ["$$typeof", "render"],
    AvatarRootProvider: ["$$typeof", "render"],
    Badge: ["$$typeof", "render"],
    BadgePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Bleed: ["$$typeof", "render"],
    BlockquoteCaption: ["$$typeof", "render"],
    BlockquoteContent: ["$$typeof", "render"],
    BlockquoteIcon: ["$$typeof", "render"],
    BlockquotePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    BlockquoteRoot: ["$$typeof", "render"],
    Box: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    BreadcrumbCurrentLink: ["$$typeof", "render"],
    BreadcrumbEllipsis: ["$$typeof", "render"],
    BreadcrumbItem: ["$$typeof", "render"],
    BreadcrumbLink: ["$$typeof", "render"],
    BreadcrumbList: ["$$typeof", "render"],
    BreadcrumbPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    BreadcrumbRoot: ["$$typeof", "render"],
    BreadcrumbSeparator: ["$$typeof", "render"],
    Button: ["$$typeof", "render"],
    ButtonGroup: ["$$typeof", "render"],
    ButtonPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    CardBody: ["$$typeof", "render"],
    CardDescription: ["$$typeof", "render"],
    CardFooter: ["$$typeof", "render"],
    CardHeader: ["$$typeof", "render"],
    CardPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    CardRoot: ["$$typeof", "render"],
    CardTitle: ["$$typeof", "render"],
    Center: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    CheckboxCardAddon: ["$$typeof", "render"],
    CheckboxCardContent: ["$$typeof", "render"],
    CheckboxCardControl: ["$$typeof", "render"],
    CheckboxCardDescription: ["$$typeof", "render"],
    CheckboxCardHiddenInput: ["$$typeof", "render"],
    CheckboxCardIndicator: ["$$typeof", "render"],
    CheckboxCardLabel: ["$$typeof", "render"],
    CheckboxCardRoot: ["$$typeof", "render"],
    CheckboxCardRootPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    CheckboxCardRootProvider: ["$$typeof", "render"],
    CheckboxControl: ["$$typeof", "render"],
    CheckboxGroup: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    CheckboxHiddenInput: ["$$typeof", "render"],
    CheckboxIndicator: ["$$typeof", "render"],
    CheckboxLabel: ["$$typeof", "render"],
    CheckboxPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    CheckboxRoot: ["$$typeof", "render"],
    CheckboxRootProvider: ["$$typeof", "render"],
    Checkmark: ["$$typeof", "render"],
    Circle: ["$$typeof", "render"],
    ClipboardControl: ["$$typeof", "render"],
    ClipboardCopyText: ["$$typeof", "render"],
    ClipboardIndicator: ["$$typeof", "render"],
    ClipboardInput: ["$$typeof", "render"],
    ClipboardLabel: ["$$typeof", "render"],
    ClipboardPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ClipboardRoot: ["$$typeof", "render"],
    ClipboardRootProvider: ["$$typeof", "render"],
    ClipboardTrigger: ["$$typeof", "render"],
    ClipboardValueText: ["$$typeof", "render"],
    CloseButton: ["$$typeof", "render"],
    Code: ["$$typeof", "render"],
    CodePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    CollapsibleContent: ["$$typeof", "render"],
    CollapsiblePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    CollapsibleRoot: ["$$typeof", "render"],
    CollapsibleRootProvider: ["$$typeof", "render"],
    CollapsibleTrigger: ["$$typeof", "render"],
    ColorPickerArea: ["$$typeof", "render"],
    ColorPickerAreaBackground: ["$$typeof", "render"],
    ColorPickerAreaThumb: ["$$typeof", "render"],
    ColorPickerChannelInput: ["$$typeof", "render"],
    ColorPickerChannelSlider: ["$$typeof", "render"],
    ColorPickerChannelSliderLabel: ["$$typeof", "render"],
    ColorPickerChannelSliderThumb: ["$$typeof", "render"],
    ColorPickerChannelSliderTrack: ["$$typeof", "render"],
    ColorPickerChannelSliderValueText: ["$$typeof", "render"],
    ColorPickerChannelText: ["$$typeof", "render"],
    ColorPickerContent: ["$$typeof", "render"],
    ColorPickerControl: ["$$typeof", "render"],
    ColorPickerEyeDropper: ["$$typeof", "render"],
    ColorPickerEyeDropperTrigger: ["$$typeof", "render"],
    ColorPickerFormatSelect: ["$$typeof", "render"],
    ColorPickerFormatTrigger: ["$$typeof", "render"],
    ColorPickerHiddenInput: ["$$typeof", "render"],
    ColorPickerInput: ["$$typeof", "render"],
    ColorPickerLabel: ["$$typeof", "render"],
    ColorPickerPositioner: ["$$typeof", "render"],
    ColorPickerPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ColorPickerRoot: ["$$typeof", "render"],
    ColorPickerRootProvider: ["$$typeof", "render"],
    ColorPickerSliders: ["$$typeof", "render"],
    ColorPickerSwatch: ["$$typeof", "render"],
    ColorPickerSwatchGroup: ["$$typeof", "render"],
    ColorPickerSwatchIndicator: ["$$typeof", "render"],
    ColorPickerSwatchTrigger: ["$$typeof", "render"],
    ColorPickerTransparencyGrid: ["$$typeof", "render"],
    ColorPickerTrigger: ["$$typeof", "render"],
    ColorPickerValueSwatch: ["$$typeof", "render"],
    ColorPickerValueText: ["$$typeof", "render"],
    ColorPickerView: ["$$typeof", "render"],
    ColorSwatch: ["$$typeof", "render"],
    ColorSwatchPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ComboboxClearTrigger: ["$$typeof", "render"],
    ComboboxContent: ["$$typeof", "render"],
    ComboboxControl: ["$$typeof", "render"],
    ComboboxEmpty: ["$$typeof", "render"],
    ComboboxIndicatorGroup: ["$$typeof", "render"],
    ComboboxInput: ["$$typeof", "render"],
    ComboboxItem: ["$$typeof", "render"],
    ComboboxItemGroup: ["$$typeof", "render"],
    ComboboxItemGroupLabel: ["$$typeof", "render"],
    ComboboxItemIndicator: ["$$typeof", "render"],
    ComboboxItemText: ["$$typeof", "render"],
    ComboboxLabel: ["$$typeof", "render"],
    ComboboxPositioner: ["$$typeof", "render"],
    ComboboxPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ComboboxRoot: ["$$typeof", "render"],
    ComboboxRootProvider: ["$$typeof", "render"],
    ComboboxTrigger: ["$$typeof", "render"],
    Container: ["$$typeof", "render"],
    ContainerPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    DataListItem: ["$$typeof", "render"],
    DataListItemLabel: ["$$typeof", "render"],
    DataListItemValue: ["$$typeof", "render"],
    DataListPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    DataListRoot: ["$$typeof", "render"],
    DialogActionTrigger: ["$$typeof", "render"],
    DialogBackdrop: ["$$typeof", "render"],
    DialogBody: ["$$typeof", "render"],
    DialogCloseTrigger: ["$$typeof", "render"],
    DialogContent: ["$$typeof", "render"],
    DialogDescription: ["$$typeof", "render"],
    DialogFooter: ["$$typeof", "render"],
    DialogHeader: ["$$typeof", "render"],
    DialogPositioner: ["$$typeof", "render"],
    DialogPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    DialogTitle: ["$$typeof", "render"],
    DialogTrigger: ["$$typeof", "render"],
    DownloadTrigger: ["$$typeof", "render"],
    DrawerActionTrigger: ["$$typeof", "render"],
    DrawerBackdrop: ["$$typeof", "render"],
    DrawerBody: ["$$typeof", "render"],
    DrawerCloseTrigger: ["$$typeof", "render"],
    DrawerContent: ["$$typeof", "render"],
    DrawerDescription: ["$$typeof", "render"],
    DrawerFooter: ["$$typeof", "render"],
    DrawerHeader: ["$$typeof", "render"],
    DrawerPositioner: ["$$typeof", "render"],
    DrawerRootPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    DrawerTitle: ["$$typeof", "render"],
    DrawerTrigger: ["$$typeof", "render"],
    EditableArea: ["$$typeof", "render"],
    EditableCancelTrigger: ["$$typeof", "render"],
    EditableControl: ["$$typeof", "render"],
    EditableEditTrigger: ["$$typeof", "render"],
    EditableInput: ["$$typeof", "render"],
    EditablePreview: ["$$typeof", "render"],
    EditablePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    EditableRoot: ["$$typeof", "render"],
    EditableRootProvider: ["$$typeof", "render"],
    EditableSubmitTrigger: ["$$typeof", "render"],
    EditableTextarea: ["$$typeof", "render"],
    Em: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    EmptyStateContent: ["$$typeof", "render"],
    EmptyStateDescription: ["$$typeof", "render"],
    EmptyStateIndicator: ["$$typeof", "render"],
    EmptyStatePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    EmptyStateRoot: ["$$typeof", "render"],
    EmptyStateTitle: ["$$typeof", "render"],
    FieldErrorIcon: ["$$typeof", "render"],
    FieldErrorText: ["$$typeof", "render"],
    FieldHelperText: ["$$typeof", "render"],
    FieldLabel: ["$$typeof", "render"],
    FieldPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    FieldRequiredIndicator: ["$$typeof", "render"],
    FieldRoot: ["$$typeof", "render"],
    FieldsetContent: ["$$typeof", "render"],
    FieldsetErrorText: ["$$typeof", "render"],
    FieldsetHelperText: ["$$typeof", "render"],
    FieldsetLegend: ["$$typeof", "render"],
    FieldsetRoot: ["$$typeof", "render"],
    FileUploadClearTrigger: ["$$typeof", "render"],
    FileUploadDropzone: ["$$typeof", "render"],
    FileUploadDropzoneContent: ["$$typeof", "render"],
    FileUploadFileText: ["$$typeof", "render"],
    FileUploadHiddenInput: ["$$typeof", "render"],
    FileUploadItem: ["$$typeof", "render"],
    FileUploadItemContent: ["$$typeof", "render"],
    FileUploadItemDeleteTrigger: ["$$typeof", "render"],
    FileUploadItemGroup: ["$$typeof", "render"],
    FileUploadItemName: ["$$typeof", "render"],
    FileUploadItemPreview: ["$$typeof", "render"],
    FileUploadItemPreviewImage: ["$$typeof", "render"],
    FileUploadItemSizeText: ["$$typeof", "render"],
    FileUploadLabel: ["$$typeof", "render"],
    FileUploadList: ["$$typeof", "render"],
    FileUploadPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    FileUploadRoot: ["$$typeof", "render"],
    FileUploadRootProvider: ["$$typeof", "render"],
    FileUploadTrigger: ["$$typeof", "render"],
    Flex: ["$$typeof", "render"],
    Float: ["$$typeof", "render"],
    FocusTrap: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    Grid: ["$$typeof", "render"],
    GridItem: ["$$typeof", "render"],
    Group: ["$$typeof", "type", "compare"],
    HStack: ["$$typeof", "render"],
    Heading: ["$$typeof", "render"],
    HeadingPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    HoverCardArrow: ["$$typeof", "render"],
    HoverCardArrowTip: ["$$typeof", "render"],
    HoverCardContent: ["$$typeof", "render"],
    HoverCardPositioner: ["$$typeof", "render"],
    HoverCardPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    HoverCardTrigger: ["$$typeof", "render"],
    Icon: ["$$typeof", "render"],
    IconButton: ["$$typeof", "render"],
    IconPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Image: ["$$typeof", "render"],
    Input: ["$$typeof", "render"],
    InputAddon: ["$$typeof", "render"],
    InputElement: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    InputGroup: ["$$typeof", "render"],
    InputPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Kbd: ["$$typeof", "render"],
    Link: ["$$typeof", "render"],
    LinkBox: ["$$typeof", "render"],
    LinkOverlay: ["$$typeof", "render"],
    LinkPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ListIndicator: ["$$typeof", "render"],
    ListItem: ["$$typeof", "render"],
    ListRoot: ["$$typeof", "render"],
    ListRootPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Loader: ["$$typeof", "render"],
    LoaderOverlay: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    Mark: ["$$typeof", "render"],
    MarkPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    MenuArrow: ["$$typeof", "render"],
    MenuArrowTip: ["$$typeof", "render"],
    MenuCheckboxItem: ["$$typeof", "render"],
    MenuContent: ["$$typeof", "render"],
    MenuContextTrigger: ["$$typeof", "render"],
    MenuIndicator: ["$$typeof", "render"],
    MenuItem: ["$$typeof", "render"],
    MenuItemCommand: ["$$typeof", "render"],
    MenuItemGroup: ["$$typeof", "render"],
    MenuItemGroupLabel: ["$$typeof", "render"],
    MenuItemIndicator: ["$$typeof", "render"],
    MenuItemText: ["$$typeof", "render"],
    MenuPositioner: ["$$typeof", "render"],
    MenuPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    MenuRadioItem: ["$$typeof", "render"],
    MenuRadioItemGroup: ["$$typeof", "render"],
    MenuSeparator: ["$$typeof", "render"],
    MenuTrigger: ["$$typeof", "render"],
    MenuTriggerItem: ["$$typeof", "render"],
    NativeSelectField: ["$$typeof", "render"],
    NativeSelectPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    NativeSelectRoot: ["$$typeof", "render"],
    NumberInputControl: ["$$typeof", "render"],
    NumberInputDecrementTrigger: ["$$typeof", "render"],
    NumberInputIncrementTrigger: ["$$typeof", "render"],
    NumberInputInput: ["$$typeof", "render"],
    NumberInputLabel: ["$$typeof", "render"],
    NumberInputPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    NumberInputRoot: ["$$typeof", "render"],
    NumberInputRootProvider: ["$$typeof", "render"],
    NumberInputScrubber: ["$$typeof", "render"],
    NumberInputValueText: ["$$typeof", "render"],
    PaginationEllipsis: ["$$typeof", "render"],
    PaginationItem: ["$$typeof", "render"],
    PaginationNextTrigger: ["$$typeof", "render"],
    PaginationPageText: ["$$typeof", "render"],
    PaginationPrevTrigger: ["$$typeof", "render"],
    PaginationPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    PaginationRoot: ["$$typeof", "render"],
    PaginationRootProvider: ["$$typeof", "render"],
    PinInputControl: ["$$typeof", "render"],
    PinInputHiddenInput: ["$$typeof", "render"],
    PinInputInput: ["$$typeof", "render"],
    PinInputLabel: ["$$typeof", "render"],
    PinInputPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    PinInputRoot: ["$$typeof", "render"],
    PinInputRootProvider: ["$$typeof", "render"],
    PopoverAnchor: ["$$typeof", "render"],
    PopoverArrow: ["$$typeof", "render"],
    PopoverArrowTip: ["$$typeof", "render"],
    PopoverBody: ["$$typeof", "render"],
    PopoverCloseTrigger: ["$$typeof", "render"],
    PopoverContent: ["$$typeof", "render"],
    PopoverDescription: ["$$typeof", "render"],
    PopoverFooter: ["$$typeof", "render"],
    PopoverHeader: ["$$typeof", "render"],
    PopoverPositioner: ["$$typeof", "render"],
    PopoverPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    PopoverTitle: ["$$typeof", "render"],
    PopoverTrigger: ["$$typeof", "render"],
    Presence: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    ProgressCircleCircle: ["$$typeof", "render"],
    ProgressCircleLabel: ["$$typeof", "render"],
    ProgressCirclePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ProgressCircleRange: ["$$typeof", "render"],
    ProgressCircleRoot: ["$$typeof", "render"],
    ProgressCircleRootProvider: ["$$typeof", "render"],
    ProgressCircleTrack: ["$$typeof", "render"],
    ProgressCircleValueText: ["$$typeof", "render"],
    ProgressLabel: ["$$typeof", "render"],
    ProgressPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ProgressRange: ["$$typeof", "render"],
    ProgressRoot: ["$$typeof", "render"],
    ProgressRootProvider: ["$$typeof", "render"],
    ProgressTrack: ["$$typeof", "render"],
    ProgressValueText: ["$$typeof", "render"],
    QrCodeFrame: ["$$typeof", "render"],
    QrCodeOverlay: ["$$typeof", "render"],
    QrCodePattern: ["$$typeof", "render"],
    QrCodePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    QrCodeRoot: ["$$typeof", "render"],
    QrCodeRootProvider: ["$$typeof", "render"],
    Quote: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    RadioCardItem: ["$$typeof", "render"],
    RadioCardItemAddon: ["$$typeof", "render"],
    RadioCardItemContent: ["$$typeof", "render"],
    RadioCardItemControl: ["$$typeof", "render"],
    RadioCardItemDescription: ["$$typeof", "render"],
    RadioCardItemHiddenInput: ["$$typeof", "render"],
    RadioCardItemIndicator: ["$$typeof", "render"],
    RadioCardItemText: ["$$typeof", "render"],
    RadioCardLabel: ["$$typeof", "render"],
    RadioCardPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    RadioCardRoot: ["$$typeof", "render"],
    RadioCardRootProvider: ["$$typeof", "render"],
    RadioGroupItem: ["$$typeof", "render"],
    RadioGroupItemControl: ["$$typeof", "render"],
    RadioGroupItemHiddenInput: ["$$typeof", "render"],
    RadioGroupItemIndicator: ["$$typeof", "render"],
    RadioGroupItemText: ["$$typeof", "render"],
    RadioGroupLabel: ["$$typeof", "render"],
    RadioGroupPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    RadioGroupRoot: ["$$typeof", "render"],
    RadioGroupRootProvider: ["$$typeof", "render"],
    Radiomark: ["$$typeof", "render"],
    RatingGroupControl: ["$$typeof", "render"],
    RatingGroupHiddenInput: ["$$typeof", "render"],
    RatingGroupItem: ["$$typeof", "render"],
    RatingGroupItemIndicator: ["$$typeof", "render"],
    RatingGroupLabel: ["$$typeof", "render"],
    RatingGroupPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    RatingGroupRoot: ["$$typeof", "render"],
    RatingGroupRootProvider: ["$$typeof", "render"],
    SegmentGroupIndicator: ["$$typeof", "render"],
    SegmentGroupItem: ["$$typeof", "render"],
    SegmentGroupItemHiddenInput: ["$$typeof", "render"],
    SegmentGroupItemText: ["$$typeof", "render"],
    SegmentGroupPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    SegmentGroupRoot: ["$$typeof", "render"],
    SegmentGroupRootProvider: ["$$typeof", "render"],
    SelectClearTrigger: ["$$typeof", "render"],
    SelectContent: ["$$typeof", "render"],
    SelectControl: ["$$typeof", "render"],
    SelectHiddenSelect: ["$$typeof", "render"],
    SelectIndicator: ["$$typeof", "render"],
    SelectIndicatorGroup: ["$$typeof", "render"],
    SelectItem: ["$$typeof", "render"],
    SelectItemGroup: ["$$typeof", "render"],
    SelectItemGroupLabel: ["$$typeof", "render"],
    SelectItemIndicator: ["$$typeof", "render"],
    SelectItemText: ["$$typeof", "render"],
    SelectLabel: ["$$typeof", "render"],
    SelectPositioner: ["$$typeof", "render"],
    SelectPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    SelectRoot: ["$$typeof", "render"],
    SelectRootProvider: ["$$typeof", "render"],
    SelectTrigger: ["$$typeof", "render"],
    SelectValueText: ["$$typeof", "render"],
    Separator: ["$$typeof", "render"],
    SeparatorPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    SimpleGrid: ["$$typeof", "render"],
    Skeleton: ["$$typeof", "render"],
    SkeletonCircle: ["$$typeof", "render"],
    SkeletonPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    SkeletonText: ["$$typeof", "render"],
    SkipNavContent: ["$$typeof", "render"],
    SkipNavLink: ["$$typeof", "render"],
    SliderControl: ["$$typeof", "render"],
    SliderDraggingIndicator: ["$$typeof", "render"],
    SliderHiddenInput: ["$$typeof", "render"],
    SliderLabel: ["$$typeof", "render"],
    SliderMarker: ["$$typeof", "render"],
    SliderMarkerGroup: ["$$typeof", "render"],
    SliderMarkerIndicator: ["$$typeof", "render"],
    SliderPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    SliderRange: ["$$typeof", "render"],
    SliderRoot: ["$$typeof", "render"],
    SliderRootProvider: ["$$typeof", "render"],
    SliderThumb: ["$$typeof", "render"],
    SliderTrack: ["$$typeof", "render"],
    SliderValueText: ["$$typeof", "render"],
    Spacer: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    Span: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    Spinner: ["$$typeof", "render"],
    SpinnerPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Square: ["$$typeof", "render"],
    Stack: ["$$typeof", "render"],
    StackSeparator: [
      "$$typeof",
      "render",
      "__emotion_real",
      "__emotion_base",
      "__emotion_forwardProp",
      "__emotion_cva",
    ],
    StatDownIndicator: ["$$typeof", "render"],
    StatGroup: ["$$typeof", "render"],
    StatHelpText: ["$$typeof", "render"],
    StatLabel: ["$$typeof", "render"],
    StatPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    StatRoot: ["$$typeof", "render"],
    StatUpIndicator: ["$$typeof", "render"],
    StatValueText: ["$$typeof", "render"],
    StatValueUnit: ["$$typeof", "render"],
    StatusIndicator: ["$$typeof", "render"],
    StatusPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    StatusRoot: ["$$typeof", "render"],
    StepsCompletedContent: ["$$typeof", "render"],
    StepsContent: ["$$typeof", "render"],
    StepsDescription: ["$$typeof", "render"],
    StepsIndicator: ["$$typeof", "render"],
    StepsItem: ["$$typeof", "render"],
    StepsList: ["$$typeof", "render"],
    StepsNextTrigger: ["$$typeof", "render"],
    StepsNumber: ["$$typeof", "render"],
    StepsPrevTrigger: ["$$typeof", "render"],
    StepsPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    StepsRoot: ["$$typeof", "render"],
    StepsRootProvider: ["$$typeof", "render"],
    StepsSeparator: ["$$typeof", "render"],
    StepsTitle: ["$$typeof", "render"],
    StepsTrigger: ["$$typeof", "render"],
    Sticky: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    Strong: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    SwitchControl: ["$$typeof", "render"],
    SwitchHiddenInput: ["$$typeof", "render"],
    SwitchIndicator: ["$$typeof", "render"],
    SwitchLabel: ["$$typeof", "render"],
    SwitchPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    SwitchRoot: ["$$typeof", "render"],
    SwitchRootProvider: ["$$typeof", "render"],
    SwitchThumb: ["$$typeof", "render"],
    SwitchThumbIndicator: ["$$typeof", "render"],
    TableBody: ["$$typeof", "render"],
    TableCaption: ["$$typeof", "render"],
    TableCell: ["$$typeof", "render"],
    TableColumn: ["$$typeof", "render"],
    TableColumnGroup: ["$$typeof", "render"],
    TableColumnHeader: ["$$typeof", "render"],
    TableFooter: ["$$typeof", "render"],
    TableHeader: ["$$typeof", "render"],
    TableRoot: ["$$typeof", "render"],
    TableRootPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    TableRow: ["$$typeof", "render"],
    TableScrollArea: [
      "$$typeof",
      "render",
      "__emotion_real",
      "__emotion_base",
      "__emotion_forwardProp",
      "__emotion_cva",
    ],
    TabsContent: ["$$typeof", "render"],
    TabsContentGroup: ["$$typeof", "render"],
    TabsIndicator: ["$$typeof", "render"],
    TabsList: ["$$typeof", "render"],
    TabsPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    TabsRoot: ["$$typeof", "render"],
    TabsRootProvider: ["$$typeof", "render"],
    TabsTrigger: ["$$typeof", "render"],
    TagCloseTrigger: ["$$typeof", "render"],
    TagEndElement: ["$$typeof", "render"],
    TagLabel: ["$$typeof", "render"],
    TagRoot: ["$$typeof", "render"],
    TagRootPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    TagStartElement: ["$$typeof", "render"],
    Text: ["$$typeof", "render"],
    TextPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Textarea: ["$$typeof", "render"],
    TextareaPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    Theme: ["$$typeof", "render"],
    TimelineConnector: ["$$typeof", "render"],
    TimelineContent: ["$$typeof", "render"],
    TimelineDescription: ["$$typeof", "render"],
    TimelineIndicator: ["$$typeof", "render"],
    TimelineItem: ["$$typeof", "render"],
    TimelineRoot: ["$$typeof", "render"],
    TimelineRootPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    TimelineSeparator: ["$$typeof", "render"],
    TimelineTitle: ["$$typeof", "render"],
    ToastActionTrigger: ["$$typeof", "render"],
    ToastCloseTrigger: ["$$typeof", "render"],
    ToastDescription: ["$$typeof", "render"],
    ToastIndicator: ["$$typeof", "render"],
    ToastRoot: ["$$typeof", "render"],
    ToastTitle: ["$$typeof", "render"],
    Toaster: ["$$typeof", "render", "__emotion_real", "__emotion_base", "__emotion_forwardProp", "__emotion_cva"],
    ToggleIndicator: ["$$typeof", "render"],
    TogglePropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    ToggleRoot: ["$$typeof", "render"],
    TooltipArrow: ["$$typeof", "render"],
    TooltipArrowTip: ["$$typeof", "render"],
    TooltipContent: ["$$typeof", "render"],
    TooltipPositioner: ["$$typeof", "render"],
    TooltipPropsProvider: [
      "$$typeof",
      "_currentValue",
      "_currentValue2",
      "_threadCount",
      "Provider",
      "Consumer",
      "_currentRenderer",
      "_currentRenderer2",
      "displayName",
    ],
    TooltipTrigger: ["$$typeof", "render"],
    VStack: ["$$typeof", "render"],
    VisuallyHidden: [
      "$$typeof",
      "render",
      "__emotion_real",
      "__emotion_base",
      "__emotion_forwardProp",
      "__emotion_cva",
    ],
    Wrap: ["$$typeof", "render"],
    WrapItem: ["$$typeof", "render"],
    chakra: [],
    defineSemanticTokens: [],
    defineTokens: [],
  },
  others: {
    AccordionContext: {
      type: "function",
      keys: [],
    },
    AccordionItemContext: {
      type: "function",
      keys: [],
    },
    ActionBarContext: {
      type: "function",
      keys: [],
    },
    ActionBarRoot: {
      type: "function",
      keys: ["displayName"],
    },
    ActionBarRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    AvatarContext: {
      type: "function",
      keys: [],
    },
    ChakraProvider: {
      type: "function",
      keys: [],
    },
    CheckboxCardContext: {
      type: "function",
      keys: [],
    },
    CheckboxContext: {
      type: "function",
      keys: [],
    },
    ClientOnly: {
      type: "function",
      keys: [],
    },
    ClipboardContext: {
      type: "function",
      keys: [],
    },
    CollapsibleContext: {
      type: "function",
      keys: [],
    },
    ColorPickerContext: {
      type: "function",
      keys: [],
    },
    ColorSwatchMix: {
      type: "function",
      keys: [],
    },
    ComboboxContext: {
      type: "function",
      keys: [],
    },
    ComboboxItemContext: {
      type: "function",
      keys: [],
    },
    DialogContext: {
      type: "function",
      keys: [],
    },
    DialogRoot: {
      type: "function",
      keys: ["displayName"],
    },
    DialogRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    DrawerContext: {
      type: "function",
      keys: [],
    },
    DrawerRoot: {
      type: "function",
      keys: ["displayName"],
    },
    DrawerRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    EditableContext: {
      type: "function",
      keys: [],
    },
    EnvironmentProvider: {
      type: "function",
      keys: [],
    },
    FieldsetContext: {
      type: "function",
      keys: [],
    },
    FileUploadContext: {
      type: "function",
      keys: [],
    },
    FileUploadItems: {
      type: "function",
      keys: [],
    },
    For: {
      type: "function",
      keys: [],
    },
    FormatByte: {
      type: "function",
      keys: ["displayName"],
    },
    FormatNumber: {
      type: "function",
      keys: ["displayName"],
    },
    Highlight: {
      type: "function",
      keys: [],
    },
    HoverCardContext: {
      type: "function",
      keys: [],
    },
    HoverCardRoot: {
      type: "function",
      keys: ["displayName"],
    },
    HoverCardRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    LocaleProvider: {
      type: "function",
      keys: [],
    },
    MenuContext: {
      type: "function",
      keys: [],
    },
    MenuItemContext: {
      type: "function",
      keys: [],
    },
    MenuRoot: {
      type: "function",
      keys: ["displayName"],
    },
    MenuRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    NativeSelectIndicator: {
      type: "function",
      keys: [],
    },
    NumberInputContext: {
      type: "function",
      keys: [],
    },
    PaginationContext: {
      type: "function",
      keys: [],
    },
    PaginationItems: {
      type: "function",
      keys: [],
    },
    PinInputContext: {
      type: "function",
      keys: [],
    },
    PopoverContext: {
      type: "function",
      keys: [],
    },
    PopoverRoot: {
      type: "function",
      keys: ["displayName"],
    },
    PopoverRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    Portal: {
      type: "function",
      keys: [],
    },
    ProgressCircleContext: {
      type: "function",
      keys: [],
    },
    ProgressContext: {
      type: "function",
      keys: [],
    },
    RadioCardContext: {
      type: "function",
      keys: [],
    },
    RadioGroupContext: {
      type: "function",
      keys: [],
    },
    RatingGroupContext: {
      type: "function",
      keys: [],
    },
    RatingGroupItemContext: {
      type: "function",
      keys: [],
    },
    RatingGroupItems: {
      type: "function",
      keys: [],
    },
    RecipePropsProvider: {
      type: "function",
      keys: [],
    },
    SegmentGroupContext: {
      type: "function",
      keys: [],
    },
    SegmentGroupItemContext: {
      type: "function",
      keys: [],
    },
    SegmentGroupItems: {
      type: "function",
      keys: [],
    },
    SelectContext: {
      type: "function",
      keys: [],
    },
    SelectItemContext: {
      type: "function",
      keys: [],
    },
    Show: {
      type: "function",
      keys: [],
    },
    SliderContext: {
      type: "function",
      keys: [],
    },
    StepsContext: {
      type: "function",
      keys: ["displayName"],
    },
    StepsItemContext: {
      type: "function",
      keys: ["displayName"],
    },
    StepsStatus: {
      type: "function",
      keys: [],
    },
    SwitchContext: {
      type: "function",
      keys: [],
    },
    TabsContext: {
      type: "function",
      keys: [],
    },
    ToggleContext: {
      type: "function",
      keys: [],
    },
    TooltipContext: {
      type: "function",
      keys: [],
    },
    TooltipRoot: {
      type: "function",
      keys: ["displayName"],
    },
    TooltipRootProvider: {
      type: "function",
      keys: ["displayName"],
    },
    createContext: {
      type: "function",
      keys: [],
    },
    createIcon: {
      type: "function",
      keys: [],
    },
    createListCollection: {
      type: "function",
      keys: [],
    },
    createOverlay: {
      type: "function",
      keys: [],
    },
    createRecipeContext: {
      type: "function",
      keys: [],
    },
    createSlotRecipeContext: {
      type: "function",
      keys: [],
    },
    createSystem: {
      type: "function",
      keys: [],
    },
    createToaster: {
      type: "function",
      keys: [],
    },
    defineAnimationStyles: {
      type: "function",
      keys: [],
    },
    defineConditions: {
      type: "function",
      keys: [],
    },
    defineConfig: {
      type: "function",
      keys: [],
    },
    defineGlobalStyles: {
      type: "function",
      keys: [],
    },
    defineKeyframes: {
      type: "function",
      keys: [],
    },
    defineLayerStyles: {
      type: "function",
      keys: [],
    },
    defineRecipe: {
      type: "function",
      keys: [],
    },
    defineSlotRecipe: {
      type: "function",
      keys: [],
    },
    defineStyle: {
      type: "function",
      keys: [],
    },
    defineTextStyles: {
      type: "function",
      keys: [],
    },
    getColorChannels: {
      type: "function",
      keys: [],
    },
    isValidSystem: {
      type: "function",
      keys: [],
    },
    mergeConfigs: {
      type: "function",
      keys: [],
    },
    mergeProps: {
      type: "function",
      keys: [],
    },
    mergeRefs: {
      type: "function",
      keys: [],
    },
    parseColor: {
      type: "function",
      keys: [],
    },
    useAccordion: {
      type: "function",
      keys: [],
    },
    useAccordionContext: {
      type: "function",
      keys: [],
    },
    useAccordionItemContext: {
      type: "function",
      keys: [],
    },
    useAccordionStyles: {
      type: "function",
      keys: [],
    },
    useActionBar: {
      type: "function",
      keys: [],
    },
    useActionBarContext: {
      type: "function",
      keys: [],
    },
    useActionBarStyles: {
      type: "function",
      keys: [],
    },
    useAlertStyles: {
      type: "function",
      keys: [],
    },
    useAvatar: {
      type: "function",
      keys: [],
    },
    useAvatarContext: {
      type: "function",
      keys: [],
    },
    useAvatarStyles: {
      type: "function",
      keys: [],
    },
    useBlockquoteStyles: {
      type: "function",
      keys: [],
    },
    useBreadcrumbStyles: {
      type: "function",
      keys: [],
    },
    useBreakpoint: {
      type: "function",
      keys: [],
    },
    useBreakpointValue: {
      type: "function",
      keys: [],
    },
    useCallbackRef: {
      type: "function",
      keys: [],
    },
    useCardStyles: {
      type: "function",
      keys: [],
    },
    useChakraContext: {
      type: "function",
      keys: [],
    },
    useCheckbox: {
      type: "function",
      keys: [],
    },
    useCheckboxCard: {
      type: "function",
      keys: [],
    },
    useCheckboxCardContext: {
      type: "function",
      keys: [],
    },
    useCheckboxCardStyles: {
      type: "function",
      keys: [],
    },
    useCheckboxContext: {
      type: "function",
      keys: [],
    },
    useCheckboxGroup: {
      type: "function",
      keys: [],
    },
    useCheckboxGroupContext: {
      type: "function",
      keys: [],
    },
    useCheckboxStyles: {
      type: "function",
      keys: [],
    },
    useClipboard: {
      type: "function",
      keys: [],
    },
    useClipboardContext: {
      type: "function",
      keys: [],
    },
    useClipboardStyles: {
      type: "function",
      keys: [],
    },
    useCollapsible: {
      type: "function",
      keys: [],
    },
    useCollapsibleContext: {
      type: "function",
      keys: [],
    },
    useCollapsibleStyles: {
      type: "function",
      keys: [],
    },
    useColorPicker: {
      type: "function",
      keys: [],
    },
    useColorPickerContext: {
      type: "function",
      keys: [],
    },
    useColorPickerStyles: {
      type: "function",
      keys: [],
    },
    useCombobox: {
      type: "function",
      keys: [],
    },
    useComboboxContext: {
      type: "function",
      keys: [],
    },
    useComboboxItemContext: {
      type: "function",
      keys: [],
    },
    useComboboxStyles: {
      type: "function",
      keys: [],
    },
    useConst: {
      type: "function",
      keys: [],
    },
    useControllableProp: {
      type: "function",
      keys: [],
    },
    useControllableState: {
      type: "function",
      keys: [],
    },
    useDataListStyles: {
      type: "function",
      keys: [],
    },
    useDialog: {
      type: "function",
      keys: [],
    },
    useDialogContext: {
      type: "function",
      keys: [],
    },
    useDialogStyles: {
      type: "function",
      keys: [],
    },
    useDisclosure: {
      type: "function",
      keys: [],
    },
    useDrawer: {
      type: "function",
      keys: [],
    },
    useDrawerContext: {
      type: "function",
      keys: [],
    },
    useDrawerStyles: {
      type: "function",
      keys: [],
    },
    useEditable: {
      type: "function",
      keys: [],
    },
    useEditableContext: {
      type: "function",
      keys: [],
    },
    useEditableStyles: {
      type: "function",
      keys: [],
    },
    useElementRect: {
      type: "function",
      keys: [],
    },
    useEmptyStateStyles: {
      type: "function",
      keys: [],
    },
    useEnvironmentContext: {
      type: "function",
      keys: [],
    },
    useFieldContext: {
      type: "function",
      keys: [],
    },
    useFieldStyles: {
      type: "function",
      keys: [],
    },
    useFieldsetContext: {
      type: "function",
      keys: [],
    },
    useFileUpload: {
      type: "function",
      keys: [],
    },
    useFileUploadContext: {
      type: "function",
      keys: [],
    },
    useFileUploadStyles: {
      type: "function",
      keys: [],
    },
    useFilter: {
      type: "function",
      keys: [],
    },
    useForceUpdate: {
      type: "function",
      keys: [],
    },
    useHighlight: {
      type: "function",
      keys: [],
    },
    useHoverCard: {
      type: "function",
      keys: [],
    },
    useHoverCardContext: {
      type: "function",
      keys: [],
    },
    useHoverCardStyles: {
      type: "function",
      keys: [],
    },
    useListCollection: {
      type: "function",
      keys: [],
    },
    useListStyles: {
      type: "function",
      keys: [],
    },
    useLiveRef: {
      type: "function",
      keys: [],
    },
    useLocaleContext: {
      type: "function",
      keys: [],
    },
    useMediaQuery: {
      type: "function",
      keys: [],
    },
    useMenu: {
      type: "function",
      keys: [],
    },
    useMenuContext: {
      type: "function",
      keys: [],
    },
    useMenuItemContext: {
      type: "function",
      keys: [],
    },
    useMenuStyles: {
      type: "function",
      keys: [],
    },
    useNativeSelectStyles: {
      type: "function",
      keys: [],
    },
    useNumberInput: {
      type: "function",
      keys: [],
    },
    useNumberInputContext: {
      type: "function",
      keys: [],
    },
    useNumberInputStyles: {
      type: "function",
      keys: [],
    },
    usePagination: {
      type: "function",
      keys: [],
    },
    usePaginationContext: {
      type: "function",
      keys: [],
    },
    usePaginationStyles: {
      type: "function",
      keys: [],
    },
    useParentRecipeProps: {
      type: "function",
      keys: [],
    },
    usePinInput: {
      type: "function",
      keys: [],
    },
    usePinInputContext: {
      type: "function",
      keys: [],
    },
    usePinInputStyles: {
      type: "function",
      keys: [],
    },
    usePopover: {
      type: "function",
      keys: [],
    },
    usePopoverContext: {
      type: "function",
      keys: [],
    },
    usePopoverStyles: {
      type: "function",
      keys: [],
    },
    usePrevious: {
      type: "function",
      keys: [],
    },
    useProgress: {
      type: "function",
      keys: [],
    },
    useProgressCircleStyles: {
      type: "function",
      keys: [],
    },
    useProgressContext: {
      type: "function",
      keys: [],
    },
    useProgressStyles: {
      type: "function",
      keys: [],
    },
    useQrCode: {
      type: "function",
      keys: [],
    },
    useQrCodeContext: {
      type: "function",
      keys: [],
    },
    useQrCodeStyles: {
      type: "function",
      keys: [],
    },
    useRadioCardContext: {
      type: "function",
      keys: [],
    },
    useRadioCardGroup: {
      type: "function",
      keys: [],
    },
    useRadioCardItemContext: {
      type: "function",
      keys: [],
    },
    useRadioCardStyles: {
      type: "function",
      keys: [],
    },
    useRadioGroup: {
      type: "function",
      keys: [],
    },
    useRadioGroupContext: {
      type: "function",
      keys: [],
    },
    useRadioGroupItemContext: {
      type: "function",
      keys: [],
    },
    useRadioGroupStyles: {
      type: "function",
      keys: [],
    },
    useRatingGroup: {
      type: "function",
      keys: [],
    },
    useRatingGroupContext: {
      type: "function",
      keys: [],
    },
    useRatingGroupItemContext: {
      type: "function",
      keys: [],
    },
    useRatingGroupStyles: {
      type: "function",
      keys: [],
    },
    useRecipe: {
      type: "function",
      keys: [],
    },
    useSafeLayoutEffect: {
      type: "function",
      keys: [],
    },
    useSegmentGroup: {
      type: "function",
      keys: [],
    },
    useSegmentGroupContext: {
      type: "function",
      keys: [],
    },
    useSegmentGroupItemContext: {
      type: "function",
      keys: [],
    },
    useSegmentGroupStyles: {
      type: "function",
      keys: [],
    },
    useSelect: {
      type: "function",
      keys: [],
    },
    useSelectContext: {
      type: "function",
      keys: [],
    },
    useSelectItemContext: {
      type: "function",
      keys: [],
    },
    useSelectStyles: {
      type: "function",
      keys: [],
    },
    useSlider: {
      type: "function",
      keys: [],
    },
    useSliderContext: {
      type: "function",
      keys: [],
    },
    useSliderStyles: {
      type: "function",
      keys: [],
    },
    useSlotRecipe: {
      type: "function",
      keys: [],
    },
    useStatStyles: {
      type: "function",
      keys: [],
    },
    useStatusStyles: {
      type: "function",
      keys: [],
    },
    useSteps: {
      type: "function",
      keys: [],
    },
    useStepsContext: {
      type: "function",
      keys: [],
    },
    useStepsItemContext: {
      type: "function",
      keys: [],
    },
    useStepsStyles: {
      type: "function",
      keys: [],
    },
    useSwitch: {
      type: "function",
      keys: [],
    },
    useSwitchContext: {
      type: "function",
      keys: [],
    },
    useSwitchStyles: {
      type: "function",
      keys: [],
    },
    useTableStyles: {
      type: "function",
      keys: [],
    },
    useTabs: {
      type: "function",
      keys: [],
    },
    useTabsContext: {
      type: "function",
      keys: [],
    },
    useTabsStyles: {
      type: "function",
      keys: [],
    },
    useTagStyles: {
      type: "function",
      keys: [],
    },
    useTimelineStyles: {
      type: "function",
      keys: [],
    },
    useToastStyles: {
      type: "function",
      keys: [],
    },
    useToggle: {
      type: "function",
      keys: [],
    },
    useToggleContext: {
      type: "function",
      keys: [],
    },
    useToggleStyles: {
      type: "function",
      keys: [],
    },
    useToken: {
      type: "function",
      keys: [],
    },
    useTooltip: {
      type: "function",
      keys: [],
    },
    useTooltipContext: {
      type: "function",
      keys: [],
    },
    useTooltipStyles: {
      type: "function",
      keys: [],
    },
    useUpdateEffect: {
      type: "function",
      keys: [],
    },
  },
}

