import type { Meta } from "@storybook/react"
import { Box } from "@chakra-ui/react"

export default {
  title: "Styled / Components / Combobox",

} 

export { ComboboxBasic as Basic } from "../__compositions__/examples/components/combobox/combobox-basic"
export { ComboboxAutoHighlight as AutoHighlight } from "../__compositions__/examples/components/combobox/combobox-autohighlight"
export { ComboboxControlled as Controlled } from "../__compositions__/examples/components/combobox/combobox-controlled"
export { ComboboxWithMultiple as Multiple } from "../__compositions__/examples/components/combobox/combobox-with-multiple"
export { ComboboxWithOptionGroup as OptionGroup } from "../__compositions__/examples/components/combobox/combobox-with-option-group"
export { ComboboxMinCharacter as MinCharacter } from "../__compositions__/examples/components/combobox/combobox-min-character"
export { ComboboxWithDisabled as Disabled } from "../__compositions__/examples/components/combobox/combobox-with-disabled"
export { ComboboxWithDisabledItem as DisabledItem } from "../__compositions__/examples/components/combobox/combobox-with-disabled-item"
export { ComboboxWithAsyncContent as Async } from "../__compositions__/examples/components/combobox/combobox-with-async-content"
export { ComboboxInPopover as WithinPopover } from "../__compositions__/examples/components/combobox/combobox-in-popover"
export { ComboboxRehydrateValue as RehydrateValue } from "../__compositions__/examples/components/combobox/combobox-rehydrate-value"
export { ComboboxWithCustomItem as CustomItem } from "../__compositions__/examples/components/combobox/combobox-with-custom-item"
export { ComboboxOpenControlled as OpenControlled } from "../__compositions__/examples/components/combobox/combobox-open-controlled"
export { ComboboxWithHighlight as Highlight } from "../__compositions__/examples/components/combobox/combobox-with-highlight"
export { ComboboxWithSizes as Sizes } from "../__compositions__/examples/components/combobox/combobox-with-sizes"
export { ComboboxWithVariants as Variants } from "../__compositions__/examples/components/combobox/combobox-with-variants"
export { ComboboxWithLinks as Links } from "../__compositions__/examples/components/combobox/combobox-with-links"
export { ComboboxOpenOnClick as OpenOnClick } from "../__compositions__/examples/components/combobox/combobox-open-on-click"
export { ComboboxWithStore as Store } from "../__compositions__/examples/components/combobox/combobox-with-store"
export { ComboboxVirtualized as Virtualized } from "../__compositions__/examples/components/combobox/combobox-virtualized"
export { ComboboxWithLimit as Limit } from "../__compositions__/examples/components/combobox/combobox-with-limit"
export { ComboboxWithPositioning as Positioning } from "../__compositions__/examples/components/combobox/combobox-with-positioning"
export { ComboboxWithCustomAnimation as CustomAnimation } from "../__compositions__/examples/components/combobox/combobox-with-custom-animation"
export { ComboboxWithInvalid as Invalid } from "../__compositions__/examples/components/combobox/combobox-with-invalid"
export { ComboboxWithInputGroup as InputGroup } from "../__compositions__/examples/components/combobox/combobox-with-input-group"
export { ComboboxWithField as Field } from "../__compositions__/examples/components/combobox/combobox-with-field"
export { ComboboxWithCustomFilter as CustomFilter } from "../__compositions__/examples/components/combobox/combobox-with-custom-filter"
export { ComboboxWithInputInContent as InputInContent } from "../__compositions__/examples/components/combobox/combobox-with-input-in-content"

export { ComboboxWithSelectionBehavior as SelectionBehavior } from "../__compositions__/examples/components/combobox/combobox-with-selection-behavior"
export { ComboboxWithCreateableOptions as CreateableOptions } from "../__compositions__/examples/components/combobox/combobox-with-createable-options"
export { ComboboxColorPicker as ColorPicker } from "../__compositions__/examples/components/combobox/combobox-color-picker"
