import { defineSlotRecipe } from '@chakra-ui/react';

export const auxToolSlotRecipe = defineSlotRecipe({
  slots: [
    'Root',
    'Button',
    'CoverRect',
    'FreeSelection',
    'Helpers',
    'Insertion',
    'DashedBox',
    'SelectionBox',
    'SelectionBoxInner',
    'Selector',
    'DragHandler',
    'NodeResizeHandler',
    'TranslateHandler',
    'SpaceBlockRulerIndicator',
    'SpaceBlockRulerH',
    'SpaceBlockRuleV',
  ],
  base: {
    Root: {
      transform: 'perspective(1px) translate3d(0, 0, 0)',
      position: 'absolute',
      width: '100%',
      height: '100%',
      top: 0,
      left: 0,
      pointerEvents: 'none',
      zIndex: 9998,
    },
    Button: {
      color: '#fff',
      backgroundColor: '#1890ff',
      borderColor: '#1890ff',
      boxShadow: '0 2px 0 rgba(0, 0, 0, 0.045)',
      _hover: {
        color: '#fff',
        background: '#40a9ff',
        borderColor: '#40a9ff',
      },
      _focus: {
        color: '#fff',
        background: '#096dd9',
        borderColor: '#096dd9',
      },
      _active: {
        color: '#fff',
        background: '#096dd9',
        borderColor: '#096dd9',
      },
    },
    CoverRect: {
      '&.dragging': {
        backgroundColor: 'rgba(24, 144, 255, 0.34)',
      },
      '&.dropping': {
        backgroundColor: 'rgba(24, 144, 255, 0.34)',
      },
    },
    FreeSelection: {
      backgroundColor: '#1890ff',
      borderColor: '#1890ff',
    },
    Helpers: {
      position: 'absolute',
      pointerEvents: 'all',
      zIndex: 10,
      userSelect: 'none',
      '& __Button': {},
      '&.button-right': {
        top: '100%',
        right: 0
      },
      '&.bottom-left': {},
      '&.bottom-center': {},
      '&.inner-top-right': {},
      '&.inner-top-left': {},
      '&.inner-bottom-right': {},
      '&.inner-bottom-left': {},
      '&.inner-bottom-center': {},
      '&.top-right': {},
      '&.top-left': {},
      '&.top-center': {},
    },
    Insertion: {
      backgroundColor: 'bg.emphasized',
    },
    DashedBox: {
      border: '1px dashed',
      '&-title': {
        color: '#333',
      },
      borderColor: 'border.info'
    },
    SelectionBox: {
      border: '2px solid #333',
      position: 'relative',
      pointerEvents: 'none',
      '&-title': {
        color: '#333',
      },
    },
    SelectionBoxInner: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    Selector: {
      marginTop: '-4px',
      animation: 'dn-animate-slide-to-top 0.2s',
      opacity: 0.8,
    },
    DragHandler: {
      cursor: 'move',
    },
    NodeResizeHandler: {
      position: 'absolute',
      width: '10px',
      height: '10px',
      pointerEvents: 'all',
      borderRadius: '10px',
      backgroundColor: '#fff',
      border: '1px solid #1890ff',
    },
    TranslateHandler: {
      position: 'absolute',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '2px',
      width: '40px',
      height: '20px',
      background: '#1890ff',
      opacity: 0.5,
      pointerEvents: 'all',
    },
    SpaceBlockRulerIndicator: {
      position: 'absolute',
      backgroundColor: '#1890ff',
      color: '#fff',
      borderRadius: '8px',
      zIndex: 2,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      '& span': {
        marginX: '6px',
        display: 'inline-block',
        fontSize: '12px',
      },
    },
    SpaceBlockRulerH: {
      position: 'absolute',
      top: '50%',
      left: 0,
      transform: 'translate(0, -50%)',
      width: '100%',
      height: '12px',
      borderLeft: '1px solid #1890ff',
      borderRight: '1px solid #1890ff',
      '&::after': {
        content: "''",
        display: 'block',
        position: 'absolute',
        top: '50%',
        left: 0,
        right: 0,
        transform: 'translate(0, -50%)',
        width: '100%',
        height: '1px',
        backgroundColor: '#1890ff',
        zIndex: 1,
      },
      '& __SpaceBlockRulerIndicator': {
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%) scale(0.7)',
      },
    },
    SpaceBlockRuleV: {
      position: 'absolute',
      top: 0,
      left: '50%',
      transform: 'translate(-50%, 0)',
      height: '100%',
      width: '12px',
      borderTop: '1px solid #1890ff',
      borderBottom: '1px solid #1890ff',
      '&::after': {
        content: "''",
        display: 'block',
        position: 'absolute',
        top: 0,
        left: '50%',
        transform: 'translate(-50%, 0)',
        height: '100%',
        width: '1px',
        backgroundColor: '#1890ff',
        zIndex: 1,
      },
      '& __SpaceBlockRulerIndicator': {
        left: '50%',
        top: '50%',
        transform: 'translate(-50%, -50%) scale(0.7)',
      },
    },
  },
});
