export enum SYSTEM_ACTOR_ID {
  AI_AGENT = "ai_agent",
  BUILDER_INFO = "builder_info",
  CONFIG = "config",
  CURRENT_APP_HISTORY = "current_app_history",
  GUIDE = "guide",
  RESOURCE = "resource",
  CURRENT_USER = "current_user",
  TEAM = "team",
  CURRENT_APP = "current_app",
  CURRENT_APP_ACTION = "current_app_action",
  CURRENT_APP_APP_INFO = "current_app_app_info",
  CURRENT_APP_COLLABORATORS = "current_app_collaborators",
  CURRENT_APP_COMPONENTS = "current_app_components",
  CURRENT_APP_CURSOR = "current_app_cursor",
  CURRENT_APP_DRAG_SHADOW = "current_app_drag_shadow",
  CURRENT_APP_EXECUTION = "current_app_execution",
  CURRENT_APP_LAYOUT_INFO = "current_app_layout_info",
}
