import { assign, setup } from "xstate"
import { configInitialState } from "./config.defaults"
import { getFromMock } from "#state-actors/mock"

export const configMachine = setup({
  types: {} as any,
  actions: {
    resetConfig: assign(({ context, event }) => {}),
    updateIllaMode: assign(({ context, event }) => {}),
    updateLeftPanel: assign(({ context, event }) => {}),
    updateRightPanel: assign(({ context, event }) => {}),
    updateBottomPanel: assign(({ context, event }) => {}),
    updateDebuggerVisible: assign(({ context, event }) => {}),
    updateShowDot: assign(({ context, event }) => {}),
    updateSelectedComponent: assign(({ context, event }) => {}),
    clearSelectedComponent: assign(({ context, event }) => {}),
    changeSelectedAction: assign(({ context, event }) => {}),
    updateCachedAction: assign(({ context, event }) => {}),
    updateCachedActionAdvancedConfigReducer: assign(({ context, event }) => {}),
    updateCachedActionMockConfigReducer: assign(({ context, event }) => {}),
    plusScale: assign(({ context, event }) => {}),
    minusScale: assign(({ context, event }) => {}),
    setExpandedKey: assign(({ context, event }) => {}),
    removeExpandedKey: assign(({ context, event }) => {}),
    updateCanvasShapeReducer: assign(({ context, event }) => {}),
    updateDevicesOnlineStatusReducer: assign(({ context, event }) => {}),
    updateWSStatusReducer: assign(({ context, event }) => {}),
    updateHoveredComponent: assign(({ context, event }) => {}),
    resetSelectedActionReducer: assign(({ context, event }) => {}),
    addExpandedWidgetReducer: assign(({ context, event }) => {}),
    removeExpandWidgetReducer: assign(({ context, event }) => {}),
    setDraggingNodeIDsReducer: assign(({ context, event }) => {}),
    setResizingNodeIDsReducer: assign(({ context, event }) => {}),
  },
  actors: {},
  guards: {},
}).createMachine({
  id: "config",
  initial: "idle",
  context: ({ input }: any) => ({
    ...configInitialState,
    ...getFromMock().config,
    ...input,
  }),
  states: {
    idle: {
      on: {
        resetConfig: { actions: ["resetConfig"] },
        updateIllaMode: { actions: ["updateIllaMode"] },
        updateLeftPanel: { actions: ["updateLeftPanel"] },
        updateRightPanel: { actions: ["updateRightPanel"] },
        updateBottomPanel: { actions: ["updateBottomPanel"] },
        updateDebuggerVisible: { actions: ["updateDebuggerVisible"] },
        updateShowDot: { actions: ["updateShowDot"] },
        updateSelectedComponent: { actions: ["updateSelectedComponent"] },
        clearSelectedComponent: { actions: ["clearSelectedComponent"] },
        changeSelectedAction: { actions: ["changeSelectedAction"] },
        updateCachedAction: { actions: ["updateCachedAction"] },
        updateCachedActionAdvancedConfig: { actions: ["updateCachedActionAdvancedConfigReducer"] },
        updateCachedActionMockConfig: { actions: ["updateCachedActionMockConfigReducer"] },
        plusScale: { actions: ["plusScale"] },
        minusScale: { actions: ["minusScale"] },
        setExpandedKey: { actions: ["setExpandedKey"] },
        removeExpandedKey: { actions: ["removeExpandedKey"] },
        updateCanvasShape: { actions: ["updateCanvasShapeReducer"] },
        updateDevicesOnlineStatus: { actions: ["updateDevicesOnlineStatusReducer"] },
        updateWSStatus: { actions: ["updateWSStatusReducer"] },
        updateHoveredComponent: { actions: ["updateHoveredComponent"] },
        resetSelectedAction: { actions: ["resetSelectedActionReducer"] },
        addExpandedWidget: { actions: ["addExpandedWidgetReducer"] },
        removeExpandWidget: { actions: ["removeExpandWidgetReducer"] },
        setDraggingNodeIDs: { actions: ["setDraggingNodeIDsReducer"] },
        setResizingNodeIDs: { actions: ["setResizingNodeIDsReducer"] },
      },
    },
  },
})
