const api_toJSON = {
  grid: {
    root: {
      type: "branch",
      data: [
        {
          type: "leaf",
          data: {
            views: ["panel_1", "panel_2", "panel_3"],
            activeView: "panel_1",
            id: "1",
          },
          size: 1018,
        },
        {
          type: "branch",
          data: [
            {
              type: "leaf",
              data: {
                views: ["panel_4", "panel_5"],
                activeView: "panel_5",
                id: "2",
              },
              size: 302,
            },
            {
              type: "branch",
              data: [
                {
                  type: "branch",
                  data: [
                    {
                      type: "leaf",
                      data: {
                        views: ["panel_7"],
                        activeView: "panel_7",
                        id: "4",
                      },
                      size: 141,
                    },
                    {
                      type: "leaf",
                      data: {
                        views: ["panel8"],
                        activeView: "panel8",
                        id: "5",
                      },
                      size: 141,
                    },
                  ],
                  size: 494,
                },
                {
                  type: "leaf",
                  data: {
                    views: ["panel_6"],
                    activeView: "panel_6",
                    id: "3",
                  },
                  size: 504,
                },
              ],
              size: 292,
            },
          ],
          size: 1008,
        },
      ],
      size: 604,
    },
    width: 2036,
    height: 604,
    orientation: "HORIZONTAL",
  },
  panels: {
    panel_1: {
      id: "panel_1",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 1",
      renderer: "always",
    },
    panel_2: {
      id: "panel_2",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 2",
    },
    panel_3: {
      id: "panel_3",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 3",
    },
    panel_4: {
      id: "panel_4",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 4",
    },
    panel_5: {
      id: "panel_5",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 5",
    },
    panel_6: {
      id: "panel_6",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 6",
    },
    panel_7: {
      id: "panel_7",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 7",
    },
    panel8: {
      id: "panel8",
      contentComponent: "default",
      tabComponent: "props.defaultTabComponent",
      title: "Panel 8",
    },
  },
  activeGroup: "1",
}

const DockviewApi = {
  components: {},
  activeGroup: {},
  activePanel: {},
  groups: [
    {
      api: {
        accessor: {},
        component: "__dockviewgroup__",
        id: "1",
        onActiveChange: {},
        onDidActiveChange: {},
        onDidActivePanelChange: {},
        onDidConstraintsChange: {},
        onDidConstraintsChangeInternal: {},
        onDidDimensionsChange: {},
        onDidFocusChange: {},
        onDidLocationChange: {},
        onDidParametersChange: {},
        onDidSizeChange: {},
        onDidVisibilityChange: {},
        onWillFocus: {},
        onWillVisibilityChange: {},
        panelUpdatesDisposable: { _disposable: {} },
        _disposables: [],
        _group: { _isDisposed: false, _disposables: [], id: "1", component: "groupview_default", api: {} },
        _height: 0,
        _isActive: true,
        _isDisposed: false,
        _isFocused: false,
        _isVisible: true,
        _onActiveChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidActiveChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidActivePanelChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidChangeFocus: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidConstraintsChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidConstraintsChangeInternal: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidDimensionChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidLocationChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidParametersChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidSizeChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onDidVisibilityChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onWillFocus: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _onWillVisibilityChange: { options: undefined, _listeners: [], _disposed: false, _event: {} },
        _parameters: {},
        _width: 1000,
        height: {},
        isActive: {},
        isDisposed: {},
        isFocused: {},
        isVisible: {},
        location: {},
        width: {},
      },
      component: "groupview_default",
      id: "1",
      onDidChange: {},
      parts: {},
      _disposables: [],
      _element: {},
      _evaluatedMaximumHeight: 9007199254740991,
      _evaluatedMaximumWidth: 9007199254740991,
      _evaluatedMinimumHeight: 100,
      _evaluatedMinimumWidth: 100,
      _height: 0,
      _isDisposed: false,
      _maximumHeight: 9007199254740991,
      _maximumWidth: 9007199254740991,
      _minimumHeight: 100,
      _minimumWidth: 100,

      _model: {},
      _onDidChange: {},
      _params: {
        accessor: {},
        params: {},
      },

      _priority: undefined,
      _snap: false,
      _width: 1000,

      activePanel: {},
      element: {},
      header: {},
      height: {},
      isActive: {},
      isDisposed: {},
      isVisible: {},
      locked: {},
      maximumHeight: {},
      maximumWidth: {},
      minimumHeight: {},
      minimumWidth: {},
      model: {},
      panels: {},
      params: {},
      priority: {},
      size: {},
      snap: {},
      width: {},
    }
  ],
  height: {},
  id: {},
  maximumHeight: {},
  maximumWidth: {},
  minimumHeight: {},
  minimumWidth: {},
  onDidActiveGroupChange: {},
  onDidActivePanelChange: {},
  onDidAddGroup: {},
  onDidAddPanel: {},
  onDidDrop: {},
  onDidLayoutChange: {},
  onDidLayoutFromJSON: {},
  onDidMaximizedGroupChange: {},
  onDidMovePanel: {},
  onDidOpenPopoutWindowFail: {},
  onDidPopoutGroupPositionChange: {},
  onDidPopoutGroupSizeChange: {},
  onDidRemoveGroup: {},
  onDidRemovePanel: {},
  onUnhandledDragOverEvent: {},
  onWillDragGroup: {},
  onWillDragPanel: {},
  onWillDrop: {},
  onWillShowOverlay: {},
  panels: [
    {
      accessor: { _isDisposed: false, _disposables: [], _disableResizing: false, _element: "", _id: "1" },
      api: {
        accessor: {
          _isDisposed: false,
          _disposables: Array(43),
          _disableResizing: false,
          _element: div.dockview - theme - replit,
          _id: "1",
        },
        component: "default",
        groupEventsDisposable: { _disposable: {} },
        id: "panel_1",
        onActiveChange: {},
        onDidActiveChange: {},
        onDidActiveGroupChange: {},
        onDidConstraintsChange: {},
        onDidConstraintsChangeInternal: {},
        onDidDimensionsChange: {},
        onDidFocusChange: {},
        onDidGroupChange: {},
        onDidLocationChange: {},
        onDidParametersChange: {},
        onDidRendererChange: {},
        onDidSizeChange: {},
        onDidTitleChange: {},
        onDidVisibilityChange: {},
        onWillFocus: {},
        onWillVisibilityChange: {},
        panel: { _isDisposed: false, _disposables: [], id: "panel_1", accessor: {}, containerApi: {} },

        _disposables: [],
        _group: { _isDisposed: false, _disposables: [], id: "1", component: "groupview_default", api: {} },
        _height: 0,
        _isActive: true,
        _isDisposed: false,
        _isFocused: false,
        _isVisible: true,
        _onActiveChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidActiveChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidActiveGroupChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidChangeFocus: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidConstraintsChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidConstraintsChangeInternal: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidDimensionChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidGroupChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidLocationChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidParametersChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidRendererChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidSizeChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidTitleChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onDidVisibilityChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onWillFocus: { options: null, _listeners: [], _disposed: false, _event: {} },
        _onWillVisibilityChange: { options: null, _listeners: [], _disposed: false, _event: {} },
        _parameters: {},
        _tabComponent: "props.defaultTabComponent",
        _width: 1000,
        group: {},
        height: {},
        isActive: {},
        isDisposed: {},
        isFocused: {},
        isGroupActive: {},
        isVisible: {},
        location: {},
        renderer: {},
        tabComponent: {},
        title: {},
        width: {},
      },
      containerApi: {
        component: {},
        activeGroup: {},
        activePanel: {},
        groups: {},
        height: {},
        id: {},
        maximumHeight: {},
        maximumWidth: {},
        minimumHeight: {},
        minimumWidth: {},
        onDidActiveGroupChange: {},
        onDidActivePanelChange: {},
        onDidAddGroup: {},
        onDidAddPanel: {},
        onDidDrop: {},
        onDidLayoutChange: {},
        onDidLayoutFromJSON: {},
        onDidMaximizedGroupChange: {},
        onDidMovePanel: {},
        onDidOpenPopoutWindowFail: {},
        onDidPopoutGroupPositionChange: {},
        onDidPopoutGroupSizeChange: {},
        onDidRemoveGroup: {},
        onDidRemovePanel: {},
        onUnhandledDragOverEvent: {},
        onWillDragGroup: {},
        onWillDragPanel: {},
        onWillDrop: {},
        onWillShowOverlay: {},
        panels: {},
        size: {},
        totalPanels: {},
        width: {},
      },
      id: "panel_1",
      view: {
        accessor: {},
        id: "panel_1",
        contentComponent: "default",
        tabComponent: "props.defaultTabComponent",
        _content: {},
      },
      _disposables: [{}, {}, {}],
      _group: { _isDisposed: false, _disposables: Array(10), id: "1", component: "groupview_default", api: {} },
      _isDisposed: false,
      _maximumHeight: null,
      _maximumWidth: null,
      _minimumHeight: null,
      _minimumWidth: null,
      _params: {},
      _renderer: "always",
      _title: "Panel 1",
      group: {},
      isDisposed: {},
      maximumHeight: {},
      maximumWidth: {},
      minimumHeight: {},
      minimumWidth: {},
      params: {},
      renderer: {},
      title: {},
    },
  ],
  size: {},
  totalPanels: {},
  width: {},
}
