export const connectionSchemaDefaults = {
  root: {
    namespaces: [],
    accesses: [],
    users: [],
  },
  namespace: {
    databases: [],
    accesses: [],
    users: [],
  },
  database: {
    tables: [],
    accesses: [],
    users: [],
    functions: [],
    models: [],
    params: [],
  },
}

export const databaseStoreDefaults = {
  isServing: false,
  servePending: false,
  currentState: "disconnected",
  latestError: "",
  isQueryActive: false,
  isGraphqlQueryActive: false,
  consoleOutput: [],
  connectionSchema: connectionSchemaDefaults,
  version: "",
  queryResponses: {},
  graphqlResponse: {},
}

export const baseSettingsDefaults = {
  behavior: {
    updateChecker: true,
    tableSuggest: true,
    variableSuggest: true,
    queryErrorChecker: true,
    enterConfirms: false,
    querySelectionExecution: true,
    querySelectionExecutionWarning: true,
    windowPinned: false,
    docsLanguage: "cli",
    versionCheckTimeout: 5,
    reconnectInterval: 3,
    queryQuickClose: true,
    strictSandbox: false,
    sidekickPanel: false,
  },
  appearance: {
    colorScheme: "dark",
    syntaxTheme: "default",
    windowScale: 100,
    editorScale: 100,
    queryLineNumbers: true,
    inspectorLineNumbers: true,
    functionLineNumbers: true,
    resultWordWrap: true,
    autoCollapseDepth: 0,
    defaultResultMode: "combined",
    defaultNoneResultMode: "show",
    defaultResultFormat: "sql",
    defaultDiagramAlgorithm: "aligned",
    defaultDiagramDirection: "ltr",
    defaultDiagramLineStyle: "metro",
    defaultDiagramLinkMode: "visible",
    defaultDiagramMode: "fields",
    defaultDiagramHoverFocus: "none",
    sidebarMode: "expandable",
    queryOrientation: "vertical",
    sidebarViews: {},
  },
  templates: {
    list: [],
  },
  serving: {
    driver: "memory",
    logLevel: "info",
    storage: "",
    executable: "",
    username: "root",
    password: "root",
    port: 8000,
    historySize: 250,
  },
  cloud: {
    databaseListMode: "grid",
    urlAuthBase: "",
    urlApiBase: "",
    urlApiMgmtBase: "",
    urlNewsfeedBase: "https://surrealdb.com",
    urlApiTicketsBase: "",
  },
  gtm: {
    origin: '',
    preview_header: "",
    debug_mode: false,
  },
}

export const baseConfigDefaults = {
  activeResource: "/overview",
  commandHistory: [],
  configVersion: 2,
  connections: [],
  featureFlags: {},
  keybindings: {},
  lastPromptedVersion: null,
  lastViewedNewsAt: null,
  onboarding: [],
  openDesignerPanels: ["general"],
  previousVersion: "3.5.3",
  sandbox: {
    id: "sandbox",
    name: "Sandbox",
    icon: 0,
    queries: [
      {
        id: "JuwQuyva2",
        type: "config",
        query: "",
        name: "New query",
        variables: "{}",
        valid: true,
        resultMode: "combined",
        resultFormat: "sql",
        noneResultMode: "show",
        showVariables: false,
      },
    ],
    activeQuery: "JuwQuyva2",
    authentication: {
      protocol: "mem",
      hostname: "",
      username: "",
      password: "",
      mode: "none",
      database: "",
      namespace: "",
      token: "",
      access: "",
      accessFields: [],
    },
    pinnedTables: [],
    queryHistory: [],
    lastNamespace: "sandbox",
    lastDatabase: "sandbox",
    designerTableList: true,
    explorerTableList: true,
    queryTabList: true,
    diagramAlgorithm: "default",
    diagramDirection: "default",
    diagramLineStyle: "default",
    diagramMode: "default",
    diagramLinkMode: "default",
    diagramHoverFocus: "default",
    graphqlQuery: "",
    graphqlVariables: "{}",
    graphqlShowVariables: false,
  },
  savedQueries: [],
  settings: baseSettingsDefaults,
}
