type RouteData = {
  path: `/${string}`
  label: string
}

export const routesData: RouteData[] = [
  { label: "Listbox", path: "/ui-collection-kit/listbox" },
  { label: "Listbox (Grid)", path: "/ui-collection-kit/listbox-grid" },
  { label: "Navigation Menu", path: "/ui-collection-kit/navigation-menu" },
  { label: "Navigation Menu (Viewport)", path: "/ui-collection-kit/navigation-menu-viewport" },
  { label: "Navigation Menu (Nested)", path: "/ui-collection-kit/navigation-menu-nested" },
  { label: "Toggle", path: "/ui-collection-kit/toggle" },
  { label: "Angle Slider", path: "/ui-collection-kit/angle-slider" },
  { label: "Steps", path: "/ui-collection-kit/steps" },
  { label: "QR Code", path: "/ui-collection-kit/qr-code" },
  { label: "Time Picker", path: "/ui-collection-kit/time-picker" },
  { label: "Signature Pad", path: "/ui-collection-kit/signature-pad" },
  { label: "Floating Panel", path: "/ui-collection-kit/floating-panel" },
  { label: "Tour", path: "/ui-collection-kit/tour" },
  { label: "Collapsible", path: "/ui-collection-kit/collapsible" },
  { label: "Clipboard", path: "/ui-collection-kit/clipboard" },
  { label: "Tree View", path: "/ui-collection-kit/tree-view" },
  { label: "Progress", path: "/ui-collection-kit/progress" },
  { label: "File Upload", path: "/ui-collection-kit/file-upload" },
  { label: "Presence", path: "/ui-collection-kit/presence" },
  { label: "Avatar", path: "/ui-collection-kit/avatar" },
  { label: "Color Picker", path: "/ui-collection-kit/color-picker" },
  { label: "Switch", path: "/ui-collection-kit/switch" },
  { label: "Carousel", path: "/ui-collection-kit/carousel" },
  { label: "Date Picker (Single)", path: "/ui-collection-kit/date-picker" },
  { label: "Date Picker (Range)", path: "/ui-collection-kit/date-picker-range" },
  { label: "Date Picker (Multi)", path: "/ui-collection-kit/date-picker-multi" },
  { label: "Select", path: "/ui-collection-kit/select" },
  { label: "Accordion", path: "/ui-collection-kit/accordion" },
  { label: "Checkbox", path: "/ui-collection-kit/checkbox" },
  { label: "Combobox", path: "/ui-collection-kit/combobox" },
  { label: "Editable", path: "/ui-collection-kit/editable" },
  { label: "Dialog", path: "/ui-collection-kit/dialog" },
  { label: "Hover Card", path: "/ui-collection-kit/hover-card" },
  { label: "Menu", path: "/ui-collection-kit/menu" },
  { label: "Menu Nested", path: "/ui-collection-kit/menu-nested" },
  { label: "Menu With options", path: "/ui-collection-kit/menu-options" },
  { label: "Context Menu", path: "/ui-collection-kit/context-menu" },
  { label: "Number Input", path: "/ui-collection-kit/number-input" },
  { label: "Pagination", path: "/ui-collection-kit/pagination" },
  { label: "Pin Input", path: "/ui-collection-kit/pin-input" },
  { label: "Popper", path: "/ui-collection-kit/popper" },
  { label: "Popover", path: "/ui-collection-kit/popover" },
  { label: "Radio Group", path: "/ui-collection-kit/radio-group" },
  { label: "Range Slider", path: "/ui-collection-kit/range-slider" },
  { label: "Rating Group", path: "/ui-collection-kit/rating-group" },
  { label: "Slider", path: "/ui-collection-kit/slider" },
  { label: "Tabs", path: "/ui-collection-kit/tabs" },
  { label: "Tags Input", path: "/ui-collection-kit/tags-input" },
  { label: "Timer (CountDown)", path: "/ui-collection-kit/timer-countdown" },
  { label: "Timer (StopWatch)", path: "/ui-collection-kit/timer-stopwatch" },
  { label: "Toast (Stacked)", path: "/ui-collection-kit/toast-stacked" },
  { label: "Toast (Overlap)", path: "/ui-collection-kit/toast-overlap" },
  { label: "Toggle Group", path: "/ui-collection-kit/toggle-group" },
  { label: "Tooltip", path: "/ui-collection-kit/tooltip" },
  { label: "Segment Control", path: "/ui-collection-kit/segment-control" },
  { label: "Splitter", path: "/ui-collection-kit/splitter" },
]
